/*
 * Console API
 *
 * Console...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Todo TODO
type Todo struct {
	// TODO
	TODO string `json:"TODO,omitempty"`
}
