openapi: 3.0.2
info:
  contact:
    url: https://github.com/moov-io/console
  description: Console...
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Console API
  version: v1
servers:
- description: Local development
  url: http://localhost:8090
tags:
- description: TODO
  name: TODO
paths:
  /TODO:
    get:
      operationId: TODO
      parameters:
      - description: Optional Request ID allows application developer to trace requests
          through the systems logs
        example: rs4f9915
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          type: string
        style: simple
      - description: Moov User ID
        explode: false
        in: header
        name: X-User-ID
        required: true
        schema:
          type: string
        style: simple
      - description: The number of items to skip before starting to collect the result
          set
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          minimum: 1
          type: integer
        style: form
      - description: The number of items to return
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          example: 10
          maximum: 100
          minimum: 0
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TODO'
          description: TODO
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid Gateway Object
      security:
      - bearerAuth: []
      - cookieAuth: []
      summary: TODO
      tags:
      - TODO
components:
  schemas:
    TODO:
      description: TODO
      example:
        TODO: TODO
      properties:
        TODO:
          description: TODO
          example: TODO
          type: string
      required:
      - todo
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
          type: string
      required:
      - error
